#!/usr/bin/env sh

alias c='clear'
alias cc='clear'
alias sl='ls'
alias sls='ls'
alias la='ls -a'
alias lf='ls -Fa'
alias ll='ls -alF'
alias lh='ls -lh'
alias l='ls -CF'
alias ..='cd ..'
alias cd..='cd ..'
alias scd='cd'
alias .='cd $HOME'
alias j='jobs -l'
alias x='exit'
alias df='df -h'
alias du='du -h'
alias duh='du -H'
alias grpe='grep' # I'm just sloppy sometimes
alias cgrep='clear && grep'
alias cgrpe=cgrep
alias netcons='lsof -i -nP'

if type VBoxManage &> /dev/null; then
  alias vb='VBoxManage'
fi

if type docker &> /dev/null; then
  alias d='docker'
  alias dctn='docker container'
  alias di='docker image'
  alias dp='docker pull'
  alias dr='docker run'
  alias dsvc='docker service'
  alias dstk='docker stack'
  alias ds='docker system'
  alias dsw='docker swarm'
  alias dv='docker volume'
  alias dn='docker network'
fi

if type kubectl &> /dev/null; then
  alias k='kubectl'
  alias ka='kubectl apply'
  alias kcfg='kubectl config'
  alias kd='kubectl describe'
  alias kg='kubectl get'
  alias ks='kubectl scale'

  if type watch &> /dev/null; then
    alias wkg='watch -n 1 kubectl get'
  fi

  function kubectl-get-pod-name-by-label() {
    kubectl get pod -l app=$1 -o jsonpath='{.items[0].metadata.name}'
  }

  alias krm='kubectl delete'
  function krmall() {
    object=$1
    for o in $(kubectl get $object --no-headers -o custom-columns=':metadata.name'); do
      kubectl delete $object --force --grace-period 0 $o
    done
  }

  function ke() {
    readonly label=${1:-'api'}
    if [[ $# -gt 1 ]]; then
      shift
      command=$@
    else
      command='bash'
    fi
    pod=$(kubectl-get-pod-name-by-label $label)
    kubectl exec -it $pod -- sh -c "$command"
  }

  alias klog='kubectl logs'
  alias klogs='klog'
  alias klf='klog -f'
  function kl() {
    label=${1:-api}
    args="${@:2}"
    pod=$(kubectl-get-pod-name-by-label $label)
    kubectl logs $pod $args
  }

  alias ck='clear && k'
  alias cka='clear && ka'
  alias ckcfg='clear && kcfg'
  alias ckd='clear && kd'
  alias ckrm='clear && krm'
  alias cke='clear && ke'
  alias ckg='clear && kg'
  alias ckl='clear && kl'

  if type kubectx &> /dev/null; then
    alias kctx='kubectx'
    alias kns='kubens'
  fi
fi

if type erl &> /dev/null; then
  alias erl='erl -config ~/.erlang-hist.config'
fi

if type terraform &> /dev/null; then
  alias tf='terraform'
  alias tfp='terraform plan'
  alias ctfp='clear && terraform plan'
  alias tfa='terraform apply'
  alias tfi='terraform import'
  alias tfs='terraform show'
  alias tfd='terraform destroy'
  alias tfw='terraform workspace'
  alias tgrep='grep --exclude-dir=terraform.tfstate.d --exclude-dir=.terraform --exclude=terraform.tfstate --exclude=terraform.tfstate.backup'
  alias tgrpe='tgrep'
  alias ctgrep='clear && tgrep'
  alias ctgrpe='ctgrep'
fi

if type tmux &> /dev/null; then
  alias t='tmux'
fi

if [[ "$OSTYPE" == darwin* ]]; then
  # open an app
  alias ot='open -a TextEdit'
  alias ok='open -a Kaleidoscope'
  alias om='open -a MacDown'
  alias of='open -a Finder'
  alias ost='open -a SourceTree'

  # grep though Ruby on Rails project and omit junk
  alias rgrep='grep --exclude-dir=assets --exclude-dir=coverage --exclude-dir=db --exclude-dir=docs --exclude-dir=log --exclude-dir=tmp'
  alias rgrpe=rgrep
  alias crgrep='clear && rgrep'
  alias crgrpe=crgrep

  if type docker &> /dev/null; then
    alias sen='docker run -v /var/run/docker.sock:/run/docker.sock -ti -e TERM tomastomecek/sen'
  fi

  # http://zanshin.net/2014/02/03/how-to-list-brew-dependencies/
  function brew-all-deps() {
    brew list | while read cask; do echo -n $fg[blue] $cask $fg[white]; brew deps $cask | awk '{printf(" %s ", $0)}'; echo ""; done
  }
fi
