#!/usr/bin/env sh

alias c=clear
alias cc=clear
alias la='ls -a'
alias lf='ls -Fa'
alias ll='ls -alF'
alias sl=ls
alias sls=ls
alias lh='ls -lh'
alias l='ls -CF'
alias ..='cd ..'
alias cd..='cd ..'
alias scd='cd'
alias .='cd $HOME'
alias h='history 25'
alias j='jobs -l'
alias x=exit
alias df='df -h'
alias du='du -h'
alias duh='du -H'

alias erl='erl -config ~/.erlang-hist.config'

alias r='source $HOME/.zshrc'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias rgrep='clear && grep --exclude-dir=log --exclude-dir=tmp --exclude-dir=test --exclude-dir=spec --exclude-dir=app/assets'
alias topcommands='history | sed "s/^[0-9 ]*//" | sed "s/ *| */\n/g" | awk "{print \$1}" | sort | uniq -c | sort -rn'
alias top10='topcommands | head -n 10'
alias top25='topcommands | head -n 25'
alias netcons='lsof -i -nP'
alias installed='dpkg --get-selections | grep -v deinstall'
alias alsarestart='pulseaudio -k && sudo alsa force-reload'
alias camera='mplayer -vf mirror -v tv:// -tv device=/dev/video0:driver=v4l2'

alias wruby='cd $HOME/workspace/ruby'
alias wgems='cd $HOME/workspace/ruby/gems'
alias werl='cd $HOME/workspace/erlang'
alias wex='cd $HOME/workspace/elixir'
