#!/usr/bin/env sh

alias c='clear'
alias cc='clear'
alias sl='ls'
alias sls='ls'
alias la='ls -a'
alias lf='ls -Fa'
alias ll='ls -alF'
alias lh='ls -lh'
alias l='ls -CF'
alias ..='cd ..'
alias cd..='cd ..'
alias scd='cd'
alias .='cd $HOME'
alias h='history 25'
alias j='jobs -l'
alias x='exit'
alias df='df -h'
alias du='du -h'
alias duh='du -H'
alias v='VBoxManage'

alias erl='erl -config ~/.erlang-hist.config'
alias t='tmux'

# I'm just sloppy sometimes
alias grpe='grep'
# clear console and grep though directory
alias cgrep='clear && grep'
# grep though Ruby on Rails project and omit junk
alias rgrep='grep --exclude-dir=assets --exclude-dir=coverage --exclude-dir=db --exclude-dir=log --exclude-dir=tmp'
# clear console and grep though Ruby on Rails project and omit junk
alias crgrep='clear && rgrep'
# grep though Scala project and omit junk
alias sgrep='grep --exclude-dir=target'
# clear console and grep though Ruby on Rails project and omit junk
alias csgrep='clear && sgrep'

alias topcmds='history | sed "s/^[0-9 ]*//" | sed "s/ *| */\n/g" | awk "{print \$1}" | sort | uniq -c | sort -rn'
alias topcmds10='topcommands | head -n 10'
alias topcmds25='topcommands | head -n 25'
alias netcons='lsof -i -nP'

alias wrb='cd $HOME/workspace/ruby'
alias wgems='cd $HOME/workspace/ruby/gems'
alias werl='cd $HOME/workspace/erlang'
alias wex='cd $HOME/workspace/elixir'

# http://zanshin.net/2014/02/03/how-to-list-brew-dependencies/
function brew-all-deps() {
	brew list | while read cask; do echo -n $fg[blue] $cask $fg[white]; brew deps $cask | awk '{printf(" %s ", $0)}'; echo ""; done
}
