#!/usr/bin/env sh

if (type ansible &> /dev/null); then
  alias a="ansible"
  alias ag="ansible-galaxy"
  alias ap="ansible-playbook"
  alias av="ansible-vault"
  alias ave="ansible-vault edit"
  alias avv="ansible-vault view"
fi
