#!/usr/bin/env sh

alias c='clear'
alias cc='clear'
alias ccat='clear && cat'
alias sl='ls'
alias sls='ls'
alias la='ls -a'
alias lf='ls -Fa'
alias ll='ls -alF'
alias lh='ls -lh'
alias l='ls -CF'
alias ..='cd ..'
alias cd..='cd ..'
alias scd='cd'
alias .='cd $HOME'
alias x='exit'
alias df='df -h'
alias du='du -h'
alias duh='du -H'
# TODO: check https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/git/git.plugin.zsh
alias g='git'
alias grpe='grep' # I'm just sloppy sometimes
alias cgrep='clear && grep'
alias gi='grep -in'
alias rg='grep -rin'
alias crg='clear && grep -rin'
alias rm='rm -v'
alias netcons='lsof -i -nP'
alias wr='__cd::workspace'
alias cwr='clear && __cd::workspace'
alias ff='__find::file'
alias fd='__find::dir'
alias first='head -n 1'
alias last='tail -n 1'
alias len='wc -c'
alias cp='cp -i'
alias mv='mv -i'
alias v="vim"
alias vo="vim -o"
alias vO="vim -O"
alias vimrc="vim ~/.vimrc"
alias vR="vim -R"
alias less="less -I"
alias cdln="__cd::ln"
alias w1="watch -n 1"
alias randline='shuf -n 1'

pwd() {
  if [ $# -eq 0 ]; then
    builtin pwd
  else
    if [ ! -d "$1" ]; then
      echo "pwd: $1: Not a directory" >&2
      return 1
    fi
    realpath "$1"
  fi
}

if (type youtube-dl &> /dev/null); then
  alias youtube-dl="youtube-dl -f best"
fi

if (type pbcopy &> /dev/null); then
  alias pbc="pbcopy"
fi


# FIXME:
# $ pwd
# /Users/kiela/workspace/dir_name1/dir_name2/dir_name3
# $ wr dotfiles/aliases/macos
# __cd::workspace:cd:6: not a directory: /Users/kiela/workspace/dotfiles/aliases/macos
# Current directory changed to: /Users/kiela/workspace/dir_name1/dir_name2/dir_name3

__cd::ln() {
  local __link="$1"
  local __target __dir

  if [[ $# -eq 0 ]]; then
    echo "Error: No symbolic link provided."
    echo "Usage: cdln <symbolic_link>"
    exit 1
  fi

  __target=$(readlink "$__link")

  #__debug "\$__link: $__link"
  #__debug "\$__target: $__target"

  if [ -z "$__target" ]; then
      __target=$(which "$__link")
      # TODO: check if __target is a symbolic link again
      #__debug "\$__target: $__target"
      if [[ -z "$__target" ]]; then
          echo "Error: Neither a valid symbolic link nor a command found for '$__link'."
          exit 1
      fi
  fi

  __dir="$(dirname "$__target")"
  #__debug "\$__dir: $__dir"

  cd "$__dir"
  #|| {
  #    echo "Error: Could not change directory to $__dir."
  #    exit 1
  #}

  echo "Current directory changed to: $(pwd)"
}

__cd::workspace() {
  local __home="${HOME}/workspace"

  if [ $# -eq 0 ]; then
    cd $__home
  else
    cd $__home/"$@"
  fi

  echo "Current directory changed to: $(pwd)"
}

__cd::workspace::completion() {
  local __home="${HOME}/workspace"

  if [[ -d "$__home" ]]; then
    _files -/ -W "$__home" -/
  else
    return 0
  fi
}

compdef __cd::workspace::completion __cd::workspace

__find::file() {
  if [[ -z "$1" ]]; then
    __find "f"
  else
    __find "f" | grep "$1"
  fi
}

__find::dir() {
  if [[ -z "$1" ]]; then
    __find "d"
  else
    __find "d" | grep "$1"
  fi
}

__find() {
  find . -type $1
}
