#!/usr/bin/env sh

alias c='clear'
alias cc='clear'
alias sl='ls'
alias sls='ls'
alias la='ls -a'
alias lf='ls -Fa'
alias ll='ls -alF'
alias lh='ls -lh'
alias l='ls -CF'
alias ..='cd ..'
alias cd..='cd ..'
alias scd='cd'
alias .='cd $HOME'
alias x='exit'
alias df='df -h'
alias du='du -h'
alias duh='du -H'
alias grpe='grep' # I'm just sloppy sometimes
alias cgrep='clear && grep'
alias cgrpe='cgrep'
alias rm='rm -v'
alias netcons='lsof -i -nP'
alias wr='cd $HOME/workspace'
alias ff='find . -type f'
alias fd='find . -type d'
alias first='head -n 1'
alias last='tail -n 1'
alias cp='cp -i'
alias mv='mv -i'
alias toff="__tmux::turn_off"
alias ton="__tmux::turn_on"
alias v="vim"

__tmux::turn_off()
{
  local __file="$HOME/.zsh_tmux_autostart_off"

  if [[ ! -e $__file ]]; then
    touch $__file
    if [[ $? -eq 0 ]]; then
      echo "Tmux has been turned off"
    else
      echo "Cannot turn off Tmux"
    fi
  else
    echo "Tmux is already turned off"
  fi
}

__tmux::turn_on()
{
  local __file="$HOME/.zsh_tmux_autostart_off"

  if [[ -e $__file ]]; then
    rm $__file >/dev/null 2>&1
    if [[ $? -eq 0 ]]; then
      echo "Tmux has been turned back on"
    else
      echo "Cannot turn Tmux back on"
    fi
  else
    echo "Tmux is already turned on"
  fi
}

if (type youtube-dl &> /dev/null); then
  alias youtube-dl="youtube-dl -f best"
fi
