#!/usr/bin/env sh

alias c='clear'
alias cc='clear'
alias sl='ls'
alias sls='ls'
alias la='ls -a'
alias lf='ls -Fa'
alias ll='ls -alF'
alias lh='ls -lh'
alias l='ls -CF'
alias ..='cd ..'
alias cd..='cd ..'
alias scd='cd'
alias .='cd $HOME'
alias x='exit'
alias df='df -h'
alias du='du -h'
alias duh='du -H'
alias grpe='grep' # I'm just sloppy sometimes
alias gi='grep -in'
alias rg='grep -rin'
alias crg='clear && grep -rin'
alias rm='rm -v'
alias netcons='lsof -i -nP'
alias wr='cd $HOME/workspace'
alias ff='find . -type f'
alias fd='find . -type d'
alias first='head -n 1'
alias last='tail -n 1'
alias len='wc -c'
alias cp='cp -i'
alias mv='mv -i'
alias v="vim"
alias vo="vim -o"
alias vO="vim -O"
alias less="less -I"

if (type youtube-dl &> /dev/null); then
  alias youtube-dl="youtube-dl -f best"
fi
