#!/usr/bin/env sh

if (type docker &> /dev/null); then
  alias d='docker'
  alias di='docker image'
  alias dps='docker ps'
  alias ds='docker system'
  alias dsc='docker scout'
  alias dv='docker volume'

  alias db='docker build'
  alias dr='docker run'
  alias dri='docker run -it'
fi
