#!/usr/bin/env sh

if type docker &> /dev/null; then
  alias d='docker'
  alias dctn='docker container'
  alias di='docker image'
  alias dp='docker pull'
  alias dr='docker run'
  alias dsvc='docker service'
  alias dstk='docker stack'
  alias ds='docker system'
  alias dsw='docker swarm'
  alias dv='docker volume'
  alias dn='docker network'
fi
