#!/usr/bin/env sh

if (type gcloud &> /dev/null); then
  __gcloud_completion="/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"

  if [ -f "$__gcloud_completion" ]; then
    source "$__gcloud_completion"
  fi

  unset __gcloud_completion
fi
