#!/usr/bin/env sh

if (type helm &> /dev/null); then
  if (type __completion::load &> /dev/null); then
    __completion::load helm
  else
    source <(helm completion zsh)
  fi

  alias h='helm'
  alias hr='helm repo'
  alias hrup='helm repo update'
  alias hs='helm search'
fi
