#!/usr/bin/env sh

if [[ "$OSTYPE" == darwin* ]]; then
  # open an app
  alias of='open -a Finder'
  alias ok='open -a Kaleidoscope'
  alias om='open -a MacDown'

  alias ot='open -a TextEdit'
  tot() {
    touch $1 && open -a TextEdit $1
  }

  ost() {
    local __current_dir=$(pwd)

    while [ "$__current_dir" != "/" ]; do
      if [ -d "$__current_dir/.git" ]; then
        open -a SourceTree $__current_dir
        return
      fi
      __current_dir=$(dirname "$__current_dir")
    done

    echo "No Git repository found."
  }

  # http://zanshin.net/2014/02/03/how-to-list-brew-dependencies/
  brew-all-deps() {
    brew list | while read cask; do echo -n $fg[blue] $cask $fg[white]; brew deps $cask | awk '{printf(" %s ", $0)}'; echo ''; done
  }
fi
