#!/usr/bin/env sh

if [[ "$OSTYPE" == darwin* ]]; then
  alias brew-all-deps='brew deps --tree --installed'
  alias of='open -a Finder'
  alias ok='open -a Kaleidoscope'
  alias om='open -a MacDown'
  alias ot='open -a TextEdit'

  # Create a new file with the given name and open it with TextEdit.
  # Arguments:
  #   $1: Name of the file
  tot() {
    touch $1 && open -a TextEdit $1
  }

  # Open SourceTree for the specified git repository.
  # Arguments:
  #   None
  ost() {
    local __current_dir=$(pwd)

    while [ "$__current_dir" != "/" ]; do
      if [ -d "$__current_dir/.git" ]; then
        open -a SourceTree $__current_dir
        return
      fi
      __current_dir=$(dirname "$__current_dir")
    done

    echo "No Git repository found."
  }
fi
