#!/usr/bin/env sh

if [[ "$OSTYPE" == darwin* ]]; then
  alias brew-all-deps='brew deps --tree --installed'
  alias of='open -a Finder'
  alias ok='open -a Kaleidoscope'
  alias om='open -a MacDown'
  alias ot='open -a TextEdit'

  # Create a new file with the given name and open it with TextEdit.
  # Arguments:
  #   $1: Name of the file
  # Usage:
  #   tot name_of_file.abc
  tot() {
    local __input="$1"

    if [ -z "$__input" ]; then
      echo "No input provided."
      return 1
    fi

    touch $__input && open -a TextEdit $__input
  }

  # Read piped input and pass it to TextEdit.
  # Arguments:
  #   None
  # Usage:
  #   any_command | cot
  cot() {
    if [ -t 0 ]; then
      echo "No input provided. Please use this function with a pipe, e.g., 'ls | cot'."
      return 1
    fi

    cat | xargs -0 echo | open -f -a TextEdit
  }

  # Open SourceTree for the specified git repository.
  # Arguments:
  #   None
  # Usage:
  #   ost
  ost() {
    local __current_dir=$(pwd)

    while [ "$__current_dir" != "/" ]; do
      if [ -d "$__current_dir/.git" ]; then
        open -a SourceTree $__current_dir
        return
      fi
      __current_dir=$(dirname "$__current_dir")
    done

    echo "No Git repository found."
    return 1
  }
fi
