#!/usr/bin/env zsh

if (type oc &> /dev/null); then
  if (type __completion::load &> /dev/null); then
    __completion::load oc
  else
    source <(oc completion zsh)
  fi

  alias ocls='oc projects'
  alias ocp='oc project'
fi
