#!/usr/bin/env sh

if [[ "$OSTYPE" == darwin* ]]; then
  # open an app
  alias ot='open -a TextEdit'
  alias ok='open -a Kaleidoscope'
  alias om='open -a MacDown'
  alias of='open -a Finder'

  ost() {
    current_dir=$(pwd)

    while [ "$current_dir" != "/" ]; do
      if [ -d "$current_dir/.git" ]; then
        open -a SourceTree $current_dir
        return
      fi
      current_dir=$(dirname "$current_dir")
    done

    echo "No Git repository found."
  }

  tot() {
    touch $1 && open -a TextEdit $1
  }

  # http://zanshin.net/2014/02/03/how-to-list-brew-dependencies/
  brew-all-deps() {
    brew list | while read cask; do echo -n $fg[blue] $cask $fg[white]; brew deps $cask | awk '{printf(" %s ", $0)}'; echo ''; done
  }

  alias bi='brew install'
  alias bs='brew search'
fi
