#!/usr/bin/env sh

if [[ "$OSTYPE" == darwin* ]]; then
  # open an app
  alias ot='open -a TextEdit'
  alias ok='open -a Kaleidoscope'
  alias om='open -a MacDown'
  alias of='open -a Finder'
  alias ost='open -a SourceTree'

  # http://zanshin.net/2014/02/03/how-to-list-brew-dependencies/
  function brew-all-deps() {
    brew list | while read cask; do echo -n $fg[blue] $cask $fg[white]; brew deps $cask | awk '{printf(" %s ", $0)}'; echo ''; done
  }

	alias bi='brew install'
	alias bs='brew search'
fi
