#!/usr/bin/env zsh

if (type terraform &> /dev/null); then
  alias tf='terraform'
  alias tfa='terraform apply'
  alias tff='terraform fmt'
  alias tfp='terraform plan'
  alias trg='grep -irn --exclude-dir=terraform.tfstate.d --exclude-dir=.terraform --exclude=terraform.tfstate --exclude=terraform.tfstate.backup'
  alias ctrg='clear && trg'
fi
