#!/usr/bin/env sh

if (type terraform &> /dev/null); then
  alias tf='terraform'
  alias tfp='terraform plan'
  alias ctfp='clear && terraform plan'
  alias tfa='terraform apply'
  alias tff='terraform fmt'
  alias tfi='terraform import'
  alias tfs='terraform show'
  alias tfd='terraform destroy'
  alias tfw='terraform workspace'
  alias tfv='terraform validate'
  alias trg='grep --exclude-dir=terraform.tfstate.d --exclude-dir=.terraform --exclude=terraform.tfstate --exclude=terraform.tfstate.backup'
  alias ctrg='clear && trg -rin'
fi
