#!/usr/bin/env sh

if (type vault &> /dev/null); then
  autoload -U +X bashcompinit && bashcompinit
  complete -o nospace -C "$(command -v vault)" vault

  alias va='vault'
  alias vakv='vault kv'
fi
